<main id='post' class='py-5 px-3'>
    <h1 class='mb-5'>Exercice blog sécurisé</h1>
    
    <article class="mb-5">
        <h2><?= $post->getTitle(); ?></h2>
        <?= $post->getContent(); ?>
    </article>
    
    <section>
        <h3>Commentaires</h3>
        <?php foreach($comments as $comment): ?>
            <div class='mb-3'>
                <strong><?= $comment->getUser()->getUsername() ?></strong>
                <p><?= $comment->getContent() ?></p>
            </div>
        <?php endforeach; ?>
        
        <?php if(isset($_SESSION['user_id'])): ?>
            <form action="index.php?route=check-comment" method="post" class="mt-4">
                <input type="hidden" name="csrf-token" value="<?= $csrf_token ?>" />
                <input type="hidden" name="post_id" value="<?= $post->getId() ?>" />
                <fieldset class="mb-3">
                    <label for="content" class="form-label">Votre commentaire :</label>
                    <textarea name="content" id="content" class="form-control" rows="4" required></textarea>
                </fieldset>
                <button type="submit" class="btn btn-primary">Publier</button>
            </form>
        <?php endif; ?>
        
    </section>
</main>